### ISSUE TITLE
VM

### ISSUE THREAD

**Issue by mkschreder** [rui314/8cc#52]
What would be really cool is if you wrote a vm module for it and have it generate vm code. That would make it easier to use as a portable C script vm. :-)

**Comment by andrewchambers** [comment]
There are many other things to be done on 8cc before this is worth looking at, but you are welcome to implement it yourself.

You should see the quake engine which used lcc and a vm for its scripting language. I don't think this is a good use for 8cc tbh.

**Comment by rui314** [comment]
Writing a VM is easier than writing a compiler for native instructions because you have control of both compilers and machines. You can define a virtual machine to which you can easily compile your code. I don't plan to add that because I'm not particularly interested in, though. So, well, this would be a good exercise for the reader. :)
